# Generated by Django 3.0.6 on 2020-05-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
